create table book (
        id bigint generated by default as identity,
        author varchar(255),
        category varchar(255),
        price float(53) not null,
        title varchar(255),
        primary key (id)
    );